In [3]:
import time

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [20]:
sig1 = np.arange(0, 8).reshape(1, -1)
sig2 = np.arange(0, 8).reshape(1, -1)
cosine_similarity(sig1, sig2)

array([[1.]])

In [13]:
sig1.shape

(8,)

In [17]:
rs = sig1.reshape(-1, 1)
rs

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [15]:
rs.shape

(1, 8)

In [16]:
sig1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
# for the console
st = time.perf_counter()
from sklearn.metrics.pairwise import cosine_similarity
cos_sim = cosine_similarity(filtered_signals_df.T)
print(f'cosine similarity (sklearn): {time.perf_counter() - st}s')

In [ ]:
from scipy.cluster.hierarchy import linkage, fcluster
st = time.perf_counter()
clustering_steps = linkage(filtered_signals_df.T, method='average', metric='cosine')
print(f'clustering (scipy): {time.perf_counter() - st}s')

# Scipy

In [55]:
from scipy.spatial.distance import cosine
s1 = [0, 1, 0]
s2 = [1, 1, 0]
cosine(s1, s2)

0.29289321881345254