In [3]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [20]:
sig1 = np.arange(0, 8).reshape(1, -1)
sig2 = np.arange(0, 8).reshape(1, -1)
cosine_similarity(sig1, sig2)

array([[1.]])

In [13]:
sig1.shape

(8,)

In [17]:
rs = sig1.reshape(-1, 1)
rs

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [15]:
rs.shape

(1, 8)

In [16]:
sig1

array([0, 1, 2, 3, 4, 5, 6, 7])